<%@ Page Title="" Language="C#" MasterPageFile="~/ATM_Application.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="ATM_Application.AboutUs" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h4>ATM APPLICATION</h4>
<p id="04d2" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <mark class="abx aby ao" style="box-sizing: inherit; cursor: pointer; background-color: rgb(232, 243, 232); color: currentcolor;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Banking</strong></mark><span>&nbsp;</span>is an industry that handles cash, credit, and other financial transactions. Banks provide a Safe place to Store extra cash and credit.They offer savings accounts, Certificates of Deposit, and checking accounts. Banks use these deposits to make loans. These loans include home mortgages, business loans, and car loans.</p>
<p id="5027" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    A Bank is a financial institution licensed to receive deposits and make loans. Two of the most common types of banks are commercial/retail and investment banks. Depending on type, a bank may also provide various financial services ranging from providing safe deposit boxes and currency exchange to retirement and wealth management.</p>
<h1 id="f91a" class="ma mb ev be mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 1.95em 0px -0.28em; font-family: sohne, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(36, 36, 36); font-style: normal; line-height: 30px; letter-spacing: -0.016em; font-weight: 600; font-size: 24px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong class="al" style="box-sizing: inherit; font-weight: inherit;">Definition</strong></h1>
<p id="4963" class="pw-post-body-paragraph lc ld ev le b lf my lh li lj mz ll lm ln na lp lq lr nb lt lu lv nc lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 0.86em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Banking</strong><span>&nbsp;</span>is defined as “Accepting of deposits of money from public for the purpose of Lending or Investment, repayable on demand or otherwise and withdrawable by cheque, draft, or otherwise”</p>
<p id="8c81" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Banking</strong><span>&nbsp;</span>can be defined as the business activity of accepting and safeguarding money owned by other individuals and entities, and then lending out this money in order to earn a profit. However, with the passage of time, the activities covered by banking business have widened and now various other services are also offered by banks. The banking services these days include issuance of debit and credit cards, providing safe custody of valuable items, lockers, ATM services and online transfer of funds across the country / world.</p>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kn ko nd" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 512px;">
        <picture style="box-sizing: inherit;">
        <img alt="" class="bg la lb c" height="370" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:512/0*uCvjou1D_u7DUhoy" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 512px; max-width: 100%; height: auto;" width="512" /></picture></div>
</figure>
<h1 id="d956" class="ma mb ev be mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 1.95em 0px -0.28em; font-family: sohne, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(36, 36, 36); font-style: normal; line-height: 30px; letter-spacing: -0.016em; font-weight: 600; font-size: 24px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong class="al" style="box-sizing: inherit; font-weight: inherit;">Objective of Bank</strong></h1>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="564b" class="lc ld ev le b lf my lh li lj mz ll lm nj na lp lq nk nb lt lu nl nc lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 0.86em; font-size: 21px;">Business objectives.</li>
    <li id="ac91" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Social objectives.</li>
</ul>
<p id="b5fe" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Business objectives</strong></p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="7516" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;">Making profits.</li>
    <li id="280c" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Providing services.</li>
    <li id="3bd4" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Currency issue.</li>
    <li id="1e32" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Creation of transaction media.</li>
    <li id="18c5" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Receiving deposit.</li>
    <li id="61a5" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Making loan.</li>
    <li id="d03d" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Ensuring safety.</li>
    <li id="87fe" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Investment.</li>
</ul>
<h2 id="521a" class="nu mb ev be mc nv nw nx mg ny nz oa mk ln ob oc od lr oe of og lv oh oi oj ok bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 1.72em 0px -0.31em; font-family: sohne, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(36, 36, 36); font-style: normal; letter-spacing: normal; font-weight: 600; line-height: 24px; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong class="al" style="box-sizing: inherit; font-weight: inherit;">Social objectives</strong></h2>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="433f" class="lc ld ev le b lf my lh li lj mz ll lm nj na lp lq nk nb lt lu nl nc lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 0.86em; font-size: 21px;">Creating savings.</li>
    <li id="2d4a" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Capital formation.</li>
    <li id="360c" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Industrialization.</li>
    <li id="b03e" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Employment.</li>
    <li id="5318" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Developing living standard.</li>
    <li id="54b3" class="lc ld ev le b lf np lh li lj nq ll lm nj nr lp lq nk ns lt lu nl nt lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; font-size: 21px; margin-top: 1.05em;">Economic development.</li>
</ul>
<h1 id="676b" class="ma mb ev be mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 1.95em 0px -0.28em; font-family: sohne, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; color: rgb(36, 36, 36); font-style: normal; line-height: 30px; letter-spacing: -0.016em; font-weight: 600; font-size: 24px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Features of Banking</h1>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="76ad" class="lc ld ev le b lf my lh li lj mz ll lm nj na lp lq nk nb lt lu nl nc lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 0.86em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Deals with money</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kw kx go ky bg kz" role="button" style="box-sizing: inherit; width: 680px; position: relative; cursor: zoom-in; z-index: auto; transition: transform 300ms cubic-bezier(0.2, 0, 0.2, 1) 0s;" tabindex="0">
        <div class="kn ko ol" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 970px;">
            <picture style="box-sizing: inherit;">
            <img alt="" class="bg la lb c" height="467" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*pwFQyrmyocQAQIj2.jpg" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 680px; max-width: 100%; height: auto;" width="700" /></picture></div>
    </div>
</figure>
<p id="4fbc" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The bank accept deposits from the public and advancing them as loans to the needy people. The deposits may be current, fixed saving etc.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="30e2" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Provide loans</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kw kx go ky bg kz" role="button" style="box-sizing: inherit; width: 680px; position: relative; cursor: zoom-in; z-index: auto; transition: transform 300ms cubic-bezier(0.2, 0, 0.2, 1) 0s;" tabindex="0">
        <div class="kn ko om" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 800px;">
            <picture style="box-sizing: inherit;">
            <img alt="" class="bg la lb c" height="393" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*aIkgAALNNijbw-DC.jpeg" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 680px; max-width: 100%; height: auto;" width="700" /></picture></div>
    </div>
</figure>
<p id="7664" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The banks are the institutions that can create credit i.e. creation of additional money for lending Thus ‘creation of credit is the unique features of banking.</p>
<p id="d885" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Banks make extra money by providing loans for different Product to the loan. The bank makes the extra money by lending money to the eligible person at certain rates.Nowadays, banks provide loans for various requirements such as study loan, car loan, home loan, personal loans, etc.Different banks provide different loans at different interest rates. You can compare the interest rates of different banks to get a loan at minimum interest rates</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="a6d1" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Middle man</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kn ko on" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 225px;">
        <picture style="box-sizing: inherit;">
        <img alt="" class="bg la lb c" height="225" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:225/0*Z_PNvBWQnHfCgyoQ.jpg" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 225px; max-width: 100%; height: auto;" width="225" /></picture></div>
</figure>
<p id="6d14" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Banks serve as a middle man from the money surplus unit to be money deficit unit. They are intermediaries, who transfer funds from savers to investors through grants for business, commerce, education, housing etc.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="3f28" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Deposits must be withdrawable</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kn ko oo" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 636px;">
        <picture style="box-sizing: inherit;">
        <img alt="" class="bg la lb c" height="320" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:636/0*egM1J_WVA9fO5anh.png" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 636px; max-width: 100%; height: auto;" width="636" /></picture></div>
</figure>
<p id="b7d4" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The deposits are usually withdrawable on demand. it may be withdrawable by cheque, draft or otherwise.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="701d" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Internet Services</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kw kx go ky bg kz" role="button" style="box-sizing: inherit; width: 680px; position: relative; cursor: zoom-in; z-index: auto; transition: transform 300ms cubic-bezier(0.2, 0, 0.2, 1) 0s;" tabindex="0">
        <div class="kn ko op" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 700px;">
            <picture style="box-sizing: inherit;">
            <img alt="" class="bg la lb c" height="503" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*3HU16BceE-WW1vSA.jpg" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 680px; max-width: 100%; height: auto;" width="700" /></picture></div>
    </div>
</figure>
<p id="0a4e" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Bank is that modern banks are also providing internet services. The development of the internet and its inclusion in the banking sector has made it even more easy for people to carry out various transactions.</p>
<p id="7b71" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Banks are providing online services through their apps. You can pay bills, buy food, go shopping without having cash with you. With the help of banking apps, you can pay for everything online.</p>
<p id="53d4" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Nowadays, more and more banks are taking their business online. It helps in making safe and risks free transactions, and there are fewer chances of stealing taxes. There are specific terms for these types of transactions, such as internet banking and mobile banking.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="cf21" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Commercial in nature</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kw kx go ky bg kz" role="button" style="box-sizing: inherit; width: 680px; position: relative; cursor: zoom-in; z-index: auto; transition: transform 300ms cubic-bezier(0.2, 0, 0.2, 1) 0s;" tabindex="0">
        <div class="kn ko om" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 800px;">
            <picture style="box-sizing: inherit;">
            <img alt="" class="bg la lb c" height="390" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:700/0*2zrDzJZI_QPZSdG0" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 680px; max-width: 100%; height: auto;" width="700" /></picture></div>
    </div>
</figure>
<p id="55ee" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Since all the banking activities of Commercial banks are carried on with the aim of Making profit, it is regarded as an commercial institution .</p>
<p id="2fbe" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    The bank uses our money to lend it to others or by investing it in profitable businesses to make profits. If you think your money is sitting in a banks locker, then you are wrong.</p>
<p id="0b1a" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    You might have digits of the money mentioned in your passbook, but you might be rotating between one person to another to make more money to the investor.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="c0a2" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Size transformation</strong></li>
</ul>
<p id="83ad" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Bank Create a reservoir of fund from the numerous small deposits collect from customer ,and than provide large loan to Investor.</p>
<ul class="" style="box-sizing: inherit; margin: 0px; padding: 0px; list-style: none none; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <li id="a457" class="lc ld ev le b lf lg lh li lj lk ll lm nj lo lp lq nk ls lt lu nl lw lx ly lz nm nn no bj" data-selectable-paragraph="" style="box-sizing: inherit; font-weight: 400; color: rgb(36, 36, 36); font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; margin-bottom: -0.46em; list-style-type: disc; margin-left: 30px; padding-left: 0px; margin-top: 2em; font-size: 21px;"><strong class="le ew" style="box-sizing: inherit; font-weight: 700; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif;">Nature of agent</strong></li>
</ul>
<figure class="ne nf ng nh ni kv kn ko paragraph-image" style="box-sizing: inherit; margin: 56px auto 0px; clear: both; color: rgba(0, 0, 0, 0.8); font-family: medium-content-sans-serif-font, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="kn ko oq" style="box-sizing: inherit; margin-left: auto; margin-right: auto; max-width: 487px;">
        <picture style="box-sizing: inherit;">
        <img alt="" class="bg la lb c" height="371" loading="lazy" role="presentation" src="https://miro.medium.com/v2/resize:fit:487/0*qXy9-Cu8LfepkY6H.png" style="box-sizing: inherit; vertical-align: middle; background-color: rgb(255, 255, 255); width: 487px; max-width: 100%; height: auto;" width="487" /></picture></div>
</figure>
<p id="3490" class="pw-post-body-paragraph lc ld ev le b lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz eo bj" data-selectable-paragraph="" style="box-sizing: inherit; margin: 2em 0px -0.46em; font-weight: 400; color: rgb(36, 36, 36); word-break: break-word; font-style: normal; line-height: 32px; letter-spacing: -0.003em; font-family: source-serif-pro, Georgia, Cambria, &quot;Times New Roman&quot;, Times, serif; font-size: 20px; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Beside the basic function of accepting deposits and lending money as a loan ,bank ,possess the characteristics of an agent because of its various agency services .</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
</asp:Content>
